### ISSUE TITLE
Please omit the final line of this lesson 

### ISSUE THREAD

**Issue by chrismetzgr** [learn-co-curriculum/js-looping-and-iteration-map-readme#1]
"Damn, it feels good to be a gangsta!"

Really y'all?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @critsmet.

We have updated the materials, removed this line and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
